# **Theory part I**

# Question 1.
Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

#Answer 1.
NumPy (Numerical Python) is a fundamental library for scientific computing and data analysis in Python. Its core strength lies in providing efficient support for large, multi-dimensional arrays and matrices, along with a vast collection of high-level mathematical functions to operate on these arrays. This significantly enhances Python's capabilities for numerical operations in several key ways:

Purpose:

Efficient Array Operations: NumPy's primary purpose is to provide a powerful N-dimensional array object (ndarray). Unlike Python's built-in lists, NumPy arrays are homogeneous (elements of the same data type) and stored contiguously in memory. This contiguous storage and type homogeneity enable highly optimized operations, making NumPy significantly faster for numerical computations compared to standard Python lists, especially for large datasets.

Mathematical and Logical Operations: NumPy offers a comprehensive suite of mathematical functions (linear algebra, Fourier transforms, random number generation, etc.) that can be directly applied to entire arrays without the need for explicit loops. This vectorized approach greatly simplifies code and accelerates computations.

Broadcasting: NumPy's broadcasting rules allow for arithmetic operations between arrays of different shapes under certain conditions, automatically expanding the smaller array to match the larger one. This eliminates the need for manual reshaping and significantly simplifies code.

Integration with Other Libraries: NumPy serves as a foundation for numerous other scientific computing libraries in Python (e.g., SciPy, Pandas, Matplotlib, scikit-learn). Its array object is often the underlying data structure for these libraries, enabling seamless data exchange and interoperability.

Advantages:

Performance: The core advantage is speed. NumPy's highly optimized C implementation provides substantial performance improvements over pure Python, especially for numerical operations.
Memory Efficiency: NumPy's homogeneous arrays are more memory-efficient than Python lists, which can store objects of different data types.
Ease of Use: The vectorized operations and broadcasting greatly simplify numerical computations, making code more concise and readable.
Versatility: NumPy supports various data types and allows for sophisticated array manipulations.
How it enhances Python:

Python, on its own, is a powerful general-purpose language but lacks efficient built-in mechanisms for numerical computation on large datasets. NumPy bridges this gap by providing specialized data structures and functions for numerical analysis. This makes Python a viable and often preferred language for scientific computing and data analysis, competing effectively with languages like MATLAB and R. NumPy's integration into the broader Python ecosystem expands Python's capabilities well beyond its original design, making it a go-to language for a wide range of scientific and data-related tasks.

# Question 2.
Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

# Answer 2

**Purpose and Advantages of NumPy in Scientific Computing and Data
 Analysis**
**Efficient Array Handling:**

NumPy provides an ndarray (n-dimensional array) data structure specifically designed for numerical data, which is more efficient in memory usage and performance than Python lists.
This structure allows scientists and analysts to handle large datasets more effectively.
High-Speed Computation:

NumPy is built for fast computations with optimized C-based functions, making it significantly faster than native Python for mathematical operations.
It is particularly useful for tasks that involve large amounts of data, such as in scientific simulations and big data processing.
Vectorized Operations:

In NumPy, operations can be applied to entire arrays at once, known as "vectorization." This removes the need for explicit loops, making code cleaner and more efficient.
For example, adding two arrays in NumPy (a + b) is far more efficient than looping through elements in Python lists.
Broadcasting:

Broadcasting allows NumPy to perform operations on arrays of different shapes (dimensions) without manually reshaping them, which simplifies operations on data of varying dimensions.
This feature is useful in fields such as machine learning, where data manipulation is frequent.
Foundation for Other Libraries:

Many scientific and data analysis libraries in Python, such as SciPy, pandas, and scikit-learn, are built on top of NumPy.
This compatibility makes it easier to work across these libraries without needing data conversions.
Enhancing Python’s Capabilities for Numerical Operations

Speed and Memory Efficiency:
NumPy’s arrays are stored in contiguous memory blocks and are typed, leading to less





#Question 3.
Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays?

#Answer 3.
import numpy as np

## Reversing a NumPy array
###Method 1: Using slicing
This is the most concise and efficient way to reverse an array.
For 1D arrays:
arr_1d = np.array([1, 2, 3, 4, 5]) reversed_arr_1d = arr_1d[::-1] print("Original 1D array:", arr_1d) print("Reversed 1D array (slicing):", reversed_arr_1d)

For 2D arrays:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) reversed_arr_2d_axis0 = arr_2d[::-1, :] # Reverses along axis 0 (rows) reversed_arr_2d_axis1 = arr_2d[:, ::-1] # Reverses along axis 1 (columns)

print("\nOriginal 2D array:") print(arr_2d) print("\nReversed 2D array (axis 0):") print(reversed_arr_2d_axis0) print("\nReversed 2D array (axis 1):") print(reversed_arr_2d_axis1)



###Method 2: Using flip() function
np.flip() is more general and allows reversing along specific axes.
reversed_arr_1d_flip = np.flip(arr_1d) print("\nReversed 1D array (flip):", reversed_arr_1d_flip)

reversed_arr_2d_flip_axis0 = np.flip(arr_2d, axis=0) # Reverses rows reversed_arr_2d_flip_axis1 = np.flip(arr_2d, axis=1) # Reverses columns

print("\nReversed 2D array (flip, axis 0):") print(reversed_arr_2d_flip_axis0) print("\nReversed 2D array (flip, axis 1):") print(reversed_arr_2d_flip_axis1)



###Method 3: Using flipud() and fliplr() functions (for 2D only)
These are specialized functions for reversing rows (flipud) and columns (fliplr)
reversed_arr_2d_flipud = np.flipud(arr_2d) # Reverses rows reversed_arr_2d_fliplr = np.fliplr(arr_2d) # Reverses columns

print("\nReversed 2D array (flipud):") print(reversed_arr_2d_flipud) print("\nReversed 2D array (fliplr):") reversed_arr_2d_fliplr

#Question 4.
How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance?


#Answer 4
import numpy as np

### Create a NumPy array with different data types
arr = np.array([1, 2, 3, 4.5, 6.7])

### Check the data type of the array
print(arr.dtype)  # Output: float64

### Access the data type of elements
print(arr[0].dtype)  # Output: float64

### Create arrays with specific data types:
int_arr = np.array([1, 2, 3], dtype=np.int32)
float_arr = np.array([1.0, 2.0, 3.0], dtype=np.float64)
bool_arr = np.array([True, False, True], dtype=bool)

print(int_arr.dtype)  # Output: int32
print(float_arr.dtype) # Output: float64
print(bool_arr.dtype) # Output: bool


# Importance of data types:

#1. Memory Management:
#####   - Data types determine the amount of memory allocated for each element in an array.
#####   - Using the correct data type can significantly reduce memory usage, especially for large arrays.
##### there's no reason to store them in 32 or 64-bit format.

#2. Performance:
#####   - Data types influence the speed of arithmetic operations and other computations.
#####   - Operations on arrays with compatible data types are generally faster than those that require type conversion.
##### Numerical operations are optimized for specific data types, meaning calculations with matching data types usually run faster, since no type coercion is required.


#3. Type Safety
 Specifying the data type helps prevent unexpected behavior from type coercion or implicit casting which can lead to errors or incorrect results.


# Example of memory efficiency:

Storing 10 million small integers in an int8 array (8 bits) vs. a int64 array (64 bits):

int8: 10,000,000 elements * 1 byte/element = 10 MB
int64: 10,000,000 elements * 8 bytes/element = 80 MB

#### An int8 array would require considerably less memory.

#Question 5.
Question 5.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

# Answer 5.

import numpy as np

## Define ndarrays
### 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", arr1)

### 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)

### 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", arr3)

# features of ndarrays:

 1. Homogeneous Data Type:  All elements in an ndarray must be of the same data type.
 This is a crucial difference from Python lists, which can contain elements of different types.

 2. Fixed Size at Creation:  The size of an ndarray is fixed when it is created.  Unlike lists,
   you can't dynamically append or remove elements without creating a new array.

3. Efficient Vectorized Operations: NumPy provides efficient vectorized operations.
   You can perform operations on entire arrays without explicit looping. This is much faster than
  iterating through a list element by element.  

 Example of vectorized operation:
print("\nAdding 2 to each element of arr1:")
print(arr1 + 2)


# 4. Broadcasting:
NumPy allows operations between arrays of different shapes under certain conditions.
    This is known as broadcasting and avoids unnecessary memory copies.

 Example of broadcasting:
print("\nMultiplying arr1 by a scalar:")
arr1 * 3

# 5. Memory Efficiency: NumPy arrays are more memory-efficient than lists because they store elements of the same data type in a contiguous block of memory.


# Differences from Python lists:


 **Homogeneity**: Lists can hold elements of different types (integers, strings, other lists, etc.), while ndarrays are homogeneous.

**Performance:**  NumPy's vectorized operations significantly outperform equivalent loops in Python lists.

**Memory Usage:** Ndarray's contiguous memory layout makes them generally more memory-efficient.

**Functionality:**  Ndarray's have built in vectorized mathematical operations, linear algebra, random number generation, Fourier transforms, etc.

# Question 6.
Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.?

# Answer 6
import numpy as np import time

Python lists
size = 1000000 list1 = list(range(size)) list2 = list(range(size))

start_time = time.time() result_list = [x * y for x, y in zip(list1, list2)] end_time = time.time() print("Python list time:", end_time - start_time)

NumPy arrays
array1 = np.arange(size) array2 = np.arange(size)

start_time = time.time() result_array = array1 * array2 end_time = time.time() print("NumPy array time:", end_time - start_time)

# Question 7.
Compare vstack) and hstack) functions in NumPy. Provide examples demonstrating their usage and output?

#Answer 7

import numpy as np

Create two sample arrays
array1 = np.array([[1, 2], [3, 4]]) array2 = np.array([[5, 6], [7, 8]])

Vertical stacking (vstack)
vertical_stack = np.vstack((array1, array2)) print("Vertical Stack:\n", vertical_stack)

Horizontal stacking (hstack)
horizontal_stack = np.hstack((array1, array2)) print("\nHorizontal Stack:\n", horizontal_stack)

Example with arrays of different shapes (vstack)
array3 = np.array([9, 10]) vstack_diff_shape = np.vstack((array1, array3)) print("\nVertical Stack (different shapes):\n", vstack_diff_shape)

Example with arrays of different shapes (hstack) - will result in an error if the number of rows don't match
Uncomment to see the error
array4 = np.array([[11], [12]])
hstack_diff_shape = np.hstack((array1, array4)) # This will raise an error
print("\nHorizontal Stack (different shapes):\n", hstack_diff_shape)
Demonstrating potential error when using hstack with incompatible shapes
try: array4 = np.array([[11], [12]]) hstack_diff_shape = np.hstack((array1, array4)) print("\nHorizontal Stack (different shapes):\n", hstack_diff_shape) except ValueError as e: print(f"\nError: {e}") print("hstack requires arrays to have the same number of rows.")

#Question 8.
Explain the differences between flipir) and flipud) methods in NumPy, including their effects on various arrays dimensions?

# Answer 8.

import numpy as np

Sample arrays
arr_1d = np.array([1, 2, 3, 4, 5]) arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

np.flip(arr, axis=None)
Reverses the order of elements in an array along the given axis.
If axis is not specified, the array is flattened before reversing.
print("Original 1D array:", arr_1d) print("Flipped 1D array:", np.flip(arr_1d)) # Reverses the entire array

print("\nOriginal 2D array:\n", arr_2d) print("Flipped 2D array (axis=0):\n", np.flip(arr_2d, axis=0)) # Reverses rows print("Flipped 2D array (axis=1):\n", np.flip(arr_2d, axis=1)) # Reverses columns print("Flipped 2D array (no axis):\n", np.flip(arr_2d)) #Flattens then reverses

print("\nOriginal 3D array:\n", arr_3d) print("Flipped 3D array (axis=0):\n", np.flip(arr_3d, axis=0)) # Reverses the order of the "matrices" print("Flipped 3D array (axis=1):\n", np.flip(arr_3d, axis=1)) # Reverses the order of the rows within each matrix print("Flipped 3D array (axis=2):\n", np.flip(arr_3d, axis=2)) # Reverses elements within each row of every matrix

np.flipud(arr)
Flips the array in the up/down direction. Equivalent to np.flip(arr, axis=0).
Only works on 1D and 2D arrays, for higher dimensions use np.flip(arr, axis=0)
print("\nOriginal 1D array:", arr_1d) print("Flipped 1D array (flipud):", np.flipud(arr_1d)) #Equivalent to np.flip(arr_1d)

print("\nOriginal 2D array:\n", arr_2d) print("Flipped 2D array (flipud):\n", np.flipud(arr_2d)) #Equivalent to np.flip(arr_2d, axis=0)

For 3D arrays and higher dimensions, np.flipud is not defined, use np.flip(arr, axis=0)

#Question 9.
Discuss the functionality of the array _split ) method in NumPy. How does it handle uneven splits?

# Answer 9.

import numpy as np

arr = np.arange(10)

This will raise a ValueError because 10 is not divisible by 3
try:
np.split(arr, 3)
except ValueError as e:
print("ValueError:", e)
Correct way to split into unequal sizes (demonstrates using array_split)
sub_arrays = np.array_split(arr, 3) sub_arrays

# Question 10..
Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

# Answer 10.

Import NumPy
import numpy as np

Vectorization
Vectorization in NumPy allows you to perform operations on entire arrays
without explicit looping. NumPy's universal functions (ufuncs) are designed
for this purpose. They operate element-wise on arrays, significantly speeding
up calculations compared to explicit Python loops.
Example:
arr1 = np.array([1, 2, 3]) arr2 = np.array([4, 5, 6])

Element-wise addition using vectorization
result = arr1 + arr2 print("Vectorized addition:", result)

Equivalent loop (less efficient):
result_loop = []
for i in range(len(arr1)):
result_loop.append(arr1[i] + arr2[i])
print(result_loop)
Broadcasting
Broadcasting extends the ability of ufuncs to operate on arrays of different
shapes and sizes. Under certain conditions, NumPy automatically expands the
smaller array to match the shape of the larger array, enabling element-wise
operations without creating copies.
Rules of Broadcasting:
1. If the arrays have different numbers of dimensions, the smaller array's
shape is padded with 1s on its left side until it has the same number of
dimensions as the larger array.
2. If the arrays have the same number of dimensions, but the sizes of their
corresponding dimensions don't match, NumPy compares the sizes of the
dimensions from right to left.
3. If the sizes of a dimension are equal or one of them is 1, the arrays
are compatible along that dimension.
4. If the sizes of a dimension don't match and neither of them is 1, an error
is raised.
Example:
arr3 = np.array([1, 2, 3]) # Shape (3,) arr4 = 5 # Scalar - Treated as an array with shape (1,) which is then broadcasted to (3,)

result_broadcasting = arr3 + arr4 print("Broadcasting:", result_broadcasting)

arr5 = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3) arr6 = np.array([10, 20, 30]) # Shape (3,) - broadcasted to (2, 3)

result = arr5 + arr6 print("Broadcasting 2:", result)

Efficiency:
Vectorization and broadcasting minimize the number of Python loops needed to
perform operations, relying on highly optimized C code. This drastically
reduces overhead and significantly improves performance, especially with
larger arrays. Avoiding explicit loops is crucial for numerical computation
with NumPy.

# **Pratical part II**

# **Question 1.)**
Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns ?

# Answer 1
 # Step-by-Step Guide
**Import NumPy:** Ensure you have NumPy imported.

**Create the Array:** Use np.random.randint to generate random integers.

**Transpose the Array:** Use the .T attribute to transpose the array.

In [ ]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Interchange its rows and columns (transpose the array)
transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[99  1 92]
 [79  6  6]
 [65  8 70]]

Transposed Array:
[[99 79 65]
 [ 1  6  8]
 [92  6 70]]


#

# Question 2
Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

# Answer 2
## Step-by-Step Guide

**Import NumPy**: Ensure NumPy is imported.

**Generate the 1D Array**: Create a 1D array with 10 elements.

**Reshape to 2x5 Array**: Use reshape method to convert it to a 2x5 array.

**Reshape to 5x2 Array:** Further reshape it into a 5x2 array.

In [2]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)
print("1D Array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\n2x5 Array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)
print("\n5x2 Array:")
print(array_5x2)


1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# Question 3.

Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

# Answer 3
# Step-by-Step Guide

**Import NumPy:** Ensure NumPy is imported.

**Create the 4x4 Array:** Use np.random.rand to generate random float values.

**Add a Border of Zeros:** Use np.pad to add the border.

In [3]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around it, resulting in a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:")
print(array_6x6)


Original 4x4 Array:
[[0.21637065 0.44334207 0.41260513 0.91861207]
 [0.44024705 0.78930706 0.50014831 0.85522261]
 [0.30299416 0.34715879 0.29572115 0.40356606]
 [0.49433111 0.08040318 0.04863566 0.66276371]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.21637065 0.44334207 0.41260513 0.91861207 0.        ]
 [0.         0.44024705 0.78930706 0.50014831 0.85522261 0.        ]
 [0.         0.30299416 0.34715879 0.29572115 0.40356606 0.        ]
 [0.         0.49433111 0.08040318 0.04863566 0.66276371 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# Question 4.

Using NumPy, create an array of integers from 10 to 60 with a step of 5.

# Answer 4
# Step-by-Step Guide

1.) Import NumPy:

First, you need to ensure that NumPy is imported. This can be done using the import numpy as np statement.

2.) Create the Array:

Use the np.arange() function to create an array. The arange function generates values within a specified range with a defined step.

The syntax for np.arange() is np.arange(start, stop, step), where start is the beginning value, stop is the end value (exclusive), and step is the interval between values.

In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)  # Note: 65 is used to include 60 in the array
print("Array from 10 to 60 with a step of 5:")
print(array)


Array from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]




Importing NumPy: import numpy as np imports the NumPy library and makes it accessible via the alias np.

Creating the Array: np.arange(10, 65, 5) generates an array starting from 10, with each subsequent value incremented by 5, up to but not including 65.

# Question 5.
Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element ?


# Answer 5.
# Step-by-Step Guide
Import NumPy: Ensure NumPy is imported.

Create the Array: Create a NumPy array of strings.

Apply Case Transformations: Use NumPy's vectorized string operations to apply case transformations.

In [5]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])
print("Original Array:")
print(arr)

# Apply uppercase transformation
uppercase_arr = np.char.upper(arr)
print("\nUppercase Transformation:")
print(uppercase_arr)

# Apply lowercase transformation
lowercase_arr = np.char.lower(arr)
print("\nLowercase Transformation:")
print(lowercase_arr)

# Apply title case transformation
titlecase_arr = np.char.title(arr)
print("\nTitle Case Transformation:")
print(titlecase_arr)

# Apply capitalize transformation
capitalize_arr = np.char.capitalize(arr)
print("\nCapitalize Transformation:")
print(capitalize_arr)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
['python' 'numpy' 'pandas']

Title Case Transformation:
['Python' 'Numpy' 'Pandas']

Capitalize Transformation:
['Python' 'Numpy' 'Pandas']



Original Array: ['python', 'numpy', 'pandas']

**Uppercase Transformation:** Converts all characters to uppercase.

**Lowercase Transformation:** Converts all characters to lowercase.

**Title Case Transformation:** Capitalizes the first letter of each word.

**Capitalize Transformation:** Capitalizes the first letter of the first word only.

#Question 6.

Generate a NumPy array of words. Insert a space between each character of every word in the array.

# Answer 6.

# Step-by-Step
Import NumPy: Ensure NumPy is imported.

Create the Array: Create a NumPy array of words.

Insert Spaces: Use NumPy's vectorized string operations to insert spaces.

In [6]:
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy'])
print("Original Array:")
print(words)

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)
print("\nArray with Spaces Between Characters:")
print(spaced_words)


Original Array:
['hello' 'world' 'numpy']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y']


**Original Array:** ['hello', 'world', 'numpy']

**Inserting Spaces:** The np.char.join(' ', words) function inserts a space between each character in the words of the array.

When you run this code, it will output the original array and the array with spaces inserted between each character of every word.

#Question 7.

 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

# Step-by-Step
Import NumPy: Ensure NumPy is imported.

Create the Arrays: Create two 2D NumPy arrays.

Perform Element-Wise Operations: Perform addition, subtraction, multiplication, and division.

In [7]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Element-wise addition
addition = np.add(array1, array2)
print("\nElement-wise Addition:")
print(addition)

# Element-wise subtraction
subtraction = np.subtract(array1, array2)
print("\nElement-wise Subtraction:")
print(subtraction)

# Element-wise multiplication
multiplication = np.multiply(array1, array2)
print("\nElement-wise Multiplication:")
print(multiplication)

# Element-wise division
division = np.divide(array1, array2)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Array Creation: array1 and array2 are two 2D arrays with shape (2, 3).

Element-Wise Operations:

Addition: np.add(array1, array2) adds corresponding elements.

Subtraction: np.subtract(array1, array2) subtracts corresponding elements.

Multiplication: np.multiply(array1, array2) multiplies corresponding elements.

Division: np.divide(array1, array2) divides corresponding elements.

# Question 8.)
Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


#Answer. 8
# Step-by-Step
Import NumPy: Ensure NumPy is imported.

Create the Identity Matrix: Use np.identity or np.eye to create the identity matrix.

Extract Diagonal Elements: Use np.diag to extract the diagonal elements.

In [9]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


Creating the Identity Matrix:

np.eye(5) creates a 5x5 identity matrix, where the diagonal elements are 1 and all other elements are 0.

Extracting Diagonal Elements:

np.diag(identity_matrix) extracts the diagonal elements of the matrix.

#Question 9.
 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

# Answer 9.
# Step-by-Step
Import NumPy: Ensure NumPy is imported.

Generate the Array: Create a 1D NumPy array with 100 random integers.

Prime Number Check: Define a function to check for prime numbers.

Filter Prime Numbers: Apply the function to filter and display prime numbers.

In [10]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)
print("Array of Random Integers:")
print(random_integers)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Array of Random Integers:
[278 843  95 811  91 483 765 562 815 472 179 833 780 402 917 567 280 466
 405 467 984 533 581 249 580 664  99 786 125 222 498 636 127 973 674 946
 302 936 490 635 168 327 262  13 294 920 825 133 634 856 754 837 137 534
   3 975 436 394 644 482 770 907 275 110 296 825 199 472 266 737  65 976
 244 571 574  72 125 237 944 932  95 390 663 344 714 308  63 807 698 878
 791 649 488 215 576 606 115 147 967 813]

Prime Numbers in the Array:
[811, 179, 467, 127, 13, 137, 3, 907, 199, 571, 967]


Generate the Array: np.random.randint(0, 1000, size=100) generates an array of 100 random integers between 0 and 1000.

Prime Number Check: The is_prime function checks if a number is prime.

Filter Prime Numbers: A list comprehension filters out prime numbers from the array.

#Question 10.
Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

# Answer 10
#Step-by-Step
Import NumPy: Ensure NumPy is imported.

Create the Array: Create a NumPy array with 30 random temperatures.

Reshape the Array: Reshape the array to have weeks as rows and days as columns.

Calculate Weekly Averages: Use NumPy to calculate the average temperature for each week.

In [13]:
import numpy as np

# Create a NumPy array with random daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, size=30)
print("Daily Temperatures for a Month:")
print(daily_temperatures)

# Reshape the array to have weeks as rows and days as columns (4 weeks, 7 days each)
weekly_temperatures = daily_temperatures.reshape(5, 6)
print("\nWeekly Temperatures:")
print(weekly_temperatures)

# Calculate and display the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)
print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for a Month:
[23 20 19 20 21 23 20 31 16 27 24 30 17 25 22 20 21 16 24 31 15 24 28 18
 29 22 17 21 17 32]

Weekly Temperatures:
[[23 20 19 20 21 23]
 [20 31 16 27 24 30]
 [17 25 22 20 21 16]
 [24 31 15 24 28 18]
 [29 22 17 21 17 32]]

Weekly Averages:
[21.         24.66666667 20.16666667 23.33333333 23.        ]


Creating the Array: np.random.randint(15, 35, size=30) generates an array with random integers between 15 and 35, representing daily temperatures for a month.

Reshape the Array: daily_temperatures.reshape(4, 7) reshapes the array into 4 weeks with 7 days each.

Calculate Weekly Averages: np.mean(weekly_temperatures, axis=1) calculates the average temperature for each week.
